### ISSUE TITLE
How to resize without maintaining aspect ratio

### ISSUE THREAD

**Issue by swapnilmishra** [hacksparrow/node-easyimage#16]
Very awesome and useful plug-in.

Just wanted to know how to resize without maintaining aspect ratio as resize() always maintains the aspect ratio. Thanks in advance.

**Comment by dolohow** [comment]
Will you accept the pull request with a new option than ignores aspect ratio?

**Comment by hacksparrow** [comment]
@dolohow as long as it is well tested, yes.
