### ISSUE TITLE
I'm getting the error: [Error: File not supported.]

### ISSUE THREAD

**Issue by rafagomes** [hacksparrow/node-easyimage#27]
But is a jpg image, do you have any tips?

**Comment by yolo2013** [comment]
Ｉhave the same issue

**Comment by Rustygames** [comment]
Me too, even though it outputs the image just fine

**Comment by PierreBrisorgueil** [comment]
same Sierra 10.12.5

**Comment by mrkmg** [comment]
Can someone with this issue please check to see if the latest release, 2.2.0, still has this issue?

**Comment by mrkmg** [comment]
Version 3.0.0 was just released. Can someone with OSX test this please?

**Comment by mrkmg** [comment]
Due to lack of feedback, I am closing this issue. If it pops up again, please either open a new issue or post here.
