### ISSUE TITLE
Name property of the callback parameter mangles file path

### ISSUE THREAD

**Issue by bionetsergey** [hacksparrow/node-easyimage#30]
When I pass the following to <code>rescrop()</code> or <code>resize()</code>:

<pre>
<code>{
  ...
  dst: 'temp/740d66ad-28a9-4d5e-a4f9-16d6645afb82.jpg'
}</code>
</pre>

The image gets processed, but the metadata returned to the callback replaces 'temp/' with a ' ', resulting in:

<pre>
<code>{
  ...
  name: ' 740d66ad-28a9-4d5e-a4f9-16d6645afb82.jpg'
}</code>
</pre>

**Comment by mrkmg** [comment]
Non-issue, working as expected.

You are expected to know the dst path, and maintain it yourself.

As @hacksparrow said, the name is will only be the file name, as is intended.
