### ISSUE TITLE
Converting multi-page PDF to PNG

### ISSUE THREAD

**Issue by shaunkatona** [hacksparrow/node-easyimage#40]
convert() returns "Error: File not supported".  Doesn't happen for single-page PDFs.

**Comment by drewrwilson** [comment]
@shaunkatona the suggestion you have above is for changing easyimage, right? Is there a way to just convert the first page using the options object sent to easyimg?

**Comment by chacliff** [comment]
Did this ever get solved?

**Comment by hacksparrow** [comment]
@chacliff nah. Will take look at it this weekend.

**Comment by yNyNyN** [comment]
I use exec() instead of convert() as workaround. You can simply specify the page number of the pdf you want to convert by adding '[0]' to the srcpdf. E.g. to convert only the first page of a pdf:
`easyimg.exec('convert ' + srcpdf + '[0] ' + ' + outputName).then(function () {
                console.log('converted PDF');
            }, function (err) {
                console.log(err);
            });`

**Comment by mrkmg** [comment]
This has been fixed in Version 3.0 #95

**Comment by drewrwilson** [comment]
🎉  🎈  thank you!
