### ISSUE TITLE
Add support for EXIF Orientation field

### ISSUE THREAD

**Issue by davidjconnolly** [hacksparrow/node-easyimage#42]
Great tool!  It would be even better if there was an option to respect the orientation parameter in the file's EXIF data.

I was using easyimage for a photo-both web app using sockets but couldn't find a way to automatically rotate incoming images from people's iPhones.

**Comment by wanming** [comment]
+1, when user upload image from iPhone, I cant get the rotate degree, the width is always bigger then height

**Comment by mrkmg** [comment]
In version 3, I would like to have an an option to auto-orient the image.

**Comment by mrkmg** [comment]
Fixed in v3. You can just use `convert()` to orient an image now.
