### ISSUE TITLE
imagemagick has crazy quoting rules

### ISSUE THREAD

**Issue by cscott** [hacksparrow/node-easyimage#43]
Nice to see the `execFile` fixes in 9333f1044ceadb324c1ea5f7148f236c16cb0587 (#41).

There's one other potential issue, which is really imagemagick's fault -- it does all sorts of crazy interpretation of filename arguments.  Thus you could pass `http://example.com` as a filename and get imagemagick to do a web request (!).

Here's the code I used to try to properly escape input filenames:
https://github.com/wikimedia/mediawiki-extensions-Collection-OfflineContentGenerator-latex_renderer/blob/37913e5b42e7cc83862d0edf781529748fd6013a/lib/index.js#L1394
and output filenames (which just need `%` protected):
https://github.com/wikimedia/mediawiki-extensions-Collection-OfflineContentGenerator-latex_renderer/blob/37913e5b42e7cc83862d0edf781529748fd6013a/lib/index.js#L1398

See http://www.imagemagick.org/Usage/files/#read_mods for some more details.  The imagemagick maintainer mentions that "I hope to add a setting (sometime during beta development) to selectively enable/disable these expansions" (http://www.imagemagick.org/discourse-server/viewtopic.php?t=20801) but as far as I can tell that hasn't been done yet.

**Comment by mrkmg** [comment]
Will potentially look at this at a future date. Closing for now.
