### ISSUE TITLE
crop() and gravity

### ISSUE THREAD

**Issue by lukaswhite** [hacksparrow/node-easyimage#45]
When you call `crop()` and explicitly provide `x` and`y` values, shouldn't `gravity` be **excluded** from the call to `imcmd`?

I couldn't seem to get it to behave the way I was expecting, and it seemed - though I may mis-understand  Imagemagick - that by forcing gravity to be `Center`, the `x` and `y` co-ordinates were effectively being ignored. I tried taking out the `gravity` flag and it behaved the way I expected it to.

**Comment by notok** [comment]
I also felt it's strange that the `gravity` option defaults to `Center`.

I think when `gravity` option is not specified, it should be `NorthWest` or excluded.

reference: http://www.imagemagick.org/Usage/crop/#crop_gravity

```
by default is relative to the top-left corner of the image.
```

**Comment by mrkmg** [comment]
I agree with @notok .

I will put this on the 3.0 todo.

**Comment by mrkmg** [comment]
As of 3.0, Gravity is no longer defaulted to center.
