### ISSUE TITLE
rescrop issue

### ISSUE THREAD

**Issue by angel1st** [hacksparrow/node-easyimage#46]
Hi there,
I am trying to use `rescrop` function with no luck however. Let me explain the case:
I have image with size (4128 x 2322) and I execute following code:

```
easyimg.rescrop({
    src: req.files.photo.path,
    dst: thumbPath,
    width: 300,
    height: 300,
    cropwidth: 300,
    cropheight: 300,
    x: 0, y: 0
}).then(function (file) {
   ...........                                        
   });                                     
}, function (err) {
    localNext(err);
});
```

Result image has dimensions (300, 169) and in fact is not suitable for thumbnail (I need square thumbnail). So my intention is to crop image by smallest dimension, which in that case would be 169 x 169.
So my question is - how can I crop image by smallest dimension?

**Comment by mrkmg** [comment]
Use the `thumbnail` function for this use case.
