### ISSUE TITLE
[Help] spawn ENOENT error.

### ISSUE THREAD

**Issue by SimoneTaliercio** [hacksparrow/node-easyimage#50]
Hi Guys, thanks for this awesome module!

Right now I'm stuck in a error and I run out of idea :_(

Did you ever experience this error message:

{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }

I tried to reinstall imagemagick and I'm running on v0.10.28 .

Thanks a LOT for your help!

**Comment by raeesaacapita** [comment]
Could anyone get this to work? Even I am facing similar issue after deploying codes?

**Comment by hacksparrow** [comment]
@raeesaacapita which version of Node and what OS?

**Comment by raeesaacapita** [comment]
Node - v5.0.0 and OS - Debian 8.

**Comment by mrkmg** [comment]
Make sure ImageMagick is installed on the server.
