### ISSUE TITLE
In some cases promise is not returned, so fail does not work

### ISSUE THREAD

**Issue by bumbu** [hacksparrow/node-easyimage#52]
In some places passed options are checked and if they does not fit requirement library reject promise. But instead of returning promise it returns `deferred.reject()` that resolved to `undefined`.

Example (from crop method): 

``` js
if (options.src === undefined) return deferred.reject(error_messages['path']);
```

If options src is not specified then `crop` method will return `undefined` instead of promise and `.then` and `.fail` callbacks will not be called.

A solution is to override all such returns to be:

``` js
if (options.src === undefined) {
  deferred.reject(error_messages['path']); 
  return deferred.promise;
}
```

**Comment by mrkmg** [comment]
Fixed in release 2.2.0
