### ISSUE TITLE
Because of gravity option it is not possible to crop at random locations

### ISSUE THREAD

**Issue by bumbu** [hacksparrow/node-easyimage#53]
By default `gravity` is set to `Center`. It seems that gravity overrides `x` and `y` options (at least on `Version: ImageMagick 6.8.9-1 Q16 x86_64 2014-05-12`. So if you want to crop starting from top-left corner you have to use gravity, but if you want to crop at x:10 and y:10 it is not possible using `crop` method.

**Comment by mrkmg** [comment]
Can you please provide example code?

**Comment by bumbu** [comment]
It's been 3 years, so no :)
I'll close it, but if someone needs it, you can reopen it.

**Comment by mrkmg** [comment]
I figured. Just started working on this and trying to clear out the back log of issues and PR's.
