### ISSUE TITLE
Error reporting problem with easyimg.thumbnail

### ISSUE THREAD

**Issue by OKNoah** [hacksparrow/node-easyimage#55]
Using the code below will not show the error. 

	function ( callback ) {
		easyimg.thumbnail({
			src: "../public/images/blogs/" + imageFileOriginal,
			dst: "../public/images/blogs/" + imageFileThumb
		}).then (
		function ( err ) {
			return console.log( "There was an error making the thumbnail: " + err )
		},
		function ( image ) {
			callback( null, image)
		})

But if I add `console.log( image )` before the last callback, it will show the error in console.

**Comment by OKNoah** [comment]
Ah, error should always come second.

**Comment by zzzend** [comment]
```javascript
.then (
    function ( image ) {
        callback( null, image)
    },
    function ( err ) {
        return console.log( "There was an error making the thumbnail: " + err )
    })
```
first arfument - succes handler, second - error handler
