### ISSUE TITLE
rescrop fails when quality is specified

### ISSUE THREAD

**Issue by barwin** [hacksparrow/node-easyimage#56]
'fill' and 'gravity' args weren't being specified properly, so you'd see errors like this:

`Error: Command failed: convert: unable to open image `^': No such file or directory`

`Error: Command failed: convert: unrecognized option `-gravityCenter'`

**Comment by manuelbieh** [comment]
Can confirm that. Same for me (Windows 7 with ImageMagick 6.8.9.)

As soon as I specify a quality I get an error:

``{ [Error: Command failed: convert.exe: unrecognized option `-gravityCenter' @ error/convert.c/ConvertImageCommand/1710.
] killed: false, code: 1, signal: null }``

Error still occurs after upgrading ImageMagick to 6.9.0.

**Comment by ThomasBormans** [comment]
I can confirm as well. (Mac OS X 10.10.2 & ImageMagick 6.9.0)
Error message:
> { [Error: Command failed: convert: unable to open image `^': No such file or directory @ error/blob.c/OpenBlob/2658.
> convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
> convert: unrecognized option `-gravitycenter' @ error/convert.c/ConvertImageCommand/1710.
> ] killed: false, code: 1, signal: null }

**Comment by mrkmg** [comment]
I do not believe this is still an issue. Please re-open if this is still a problem
