### ISSUE TITLE
easyimage.info emit wrong image information.

### ISSUE THREAD

**Issue by breaklee** [hacksparrow/node-easyimage#59]
i'm using some image to get width, height.

but result of easyimage.info is not same original.

   original : W:2000, H:3000, 
    filInfo : W:3000,  H:2000

how can i fix this?

**Comment by rkurbatov** [comment]
It can be orientation flag issue. Physically image has 3000 2000 dimensions with orientation flag set to rotate it automatically.

**Comment by mrkmg** [comment]
Non-issue
