### ISSUE TITLE
Path to ImageMagick convert command ambiguous on Windows

### ISSUE THREAD

**Issue by sci-kuk** [hacksparrow/node-easyimage#63]
In Windows 7 the convert command is available by default in the environment variable PATH and points to the built-in conversion tool for volumes on a disk. Thus, when detecting if ImageMagick is installed using convert -version or when converting an image, the command fails. Ideally, there should be an optional configuration for the path to ImageMagick for easimage when included in a Node.js application.

**Comment by bendulum** [comment]
A possible workaround for this is adding the path to imagemagick to the front of the PATH. So I heard.
I haven't managed to get imagemagick + easyimage to run on Windows correctly.

**Comment by bendulum** [comment]
When I run the following in the CMD:

`identify -version` >
Version: ImageMagick 6.9.0-8 Q8 x64 2015-02-21 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC OpenMP
....

`convert -version` > 
Version: ImageMagick 6.9.0-8 Q8 x64 2015-02-21 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC OpenMP
....

So ImageMagick is installed and available. The following works as well:

`convert logo: logo.gif`
`imdisplay logo.gif`

Easyimage works on one of my machines, Win10, with ImageMagick installed before installing Easyimage.
It does not work on the second machine, Win7, with ImageMagick installed after installing Easyimage.
(Order should not matter though...)
On the first machine I never got the `ImageMagick Not Found` message, which I get on the second.

**Comment by bendulum** [comment]
I've got it working now on machine 1, using `ImageMagick-6.7.9-3-Q16-windows-x64-static`
I added `C:\Program Files\ImageMagick-6.7.9-Q16;` to the front of my PATH.

Be advised though, according to [this](http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=29785&hilit=windows) as of IM v7 `convert` is replaced by `magick`.
This is relevant for the maintainers of node-easyimage @hacksparrow

**Comment by mrkmg** [comment]
Fixed in 2.2.0 release
