### ISSUE TITLE
flatten flag should be configurable

### ISSUE THREAD

**Issue by marian2js** [hacksparrow/node-easyimage#64]
Hello, I saw that you added a new flag "-background".

I want to resize a png with transparent background conversing that background.
So in the options I used backgroud: 'none'.
But, it doesn't work, because while -flatten option is added, background doesn't work.

So, it will be great if you allow as to config flatten option, or, you can detect if background === 'none' and remove flatten.

Thanks!

**Comment by hacksparrow** [comment]
You can configure the `flatten` option now in 1.4.0. It all looks good, please close this issue.

**Comment by marian2js** [comment]
It looks great, thank you :)

**Comment by hacksparrow** [comment]
Update in 2.0.0:

i. `flatten` is `false` by default.
ii. Setting a `background` property will apply the background color (supports transparency for relevant image types) and flatten the image.
