### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by codermite** [hacksparrow/node-easyimage#71]
Im having this error,

```
 /www/default/node_modules/easyimage/easyimage.js:45
        return parseFloat(sizeArray[1]) * unit[sizeArray[2]];
                                   ^
TypeError: Cannot read property '1' of null
    at parseSize (/www/default/node_modules/easyimage/easyimage.js:45:30)
```

....

**Comment by hacksparrow** [comment]
Please type `identify <path to the image>` and paste here what you get.

**Comment by miyu-dzai-zhonguo** [comment]
avatar.png PNG 215x215 215x215+0+0 8-bit DirectClass 27.1kb

**Comment by terencemutizwa** [comment]
me too, centos

**Comment by terencemutizwa** [comment]
i fixed this by commenting out the parseSize on line 60
```
 info.size    = temp[4];//parseSize(temp[4]);

**Comment by awHamer** [comment]
Have the same problem centos 6.6
imagemagick 6.6
With imagemagick 6.9 this problem is gone.

**Comment by bORm** [comment]
Please add to requirements ( need imagemagick  >= 6.9 )

**Comment by fettay** [comment]
I had the same issue on  Debian, just try to reinstall Imagemagick (apt-get install imagemagick or equivalent) uninstalling other versions

**Comment by stiff** [comment]
In info function there is a regex, but it's not needed in older imagemagicks, because sizeString is already a number:

`return sizeArray ? parseFloat(sizeArray[1]) * unit[sizeArray[2]] : 1 * sizeString`

fixes that

**Comment by mrkmg** [comment]
Closing due to age.
