### ISSUE TITLE
Incorrect name for multiframe gifs

### ISSUE THREAD

**Issue by rkurbatov** [hacksparrow/node-easyimage#76]
info() function returns incorrect name of such files: 
name: 'ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-3503656463-1444303244814.gifGIF 8 250 246 0B 72 72 ezgif-...
repeating its name corresponding to frame number.

Additionaly i'd like to have this frame amount if possible.

**Comment by rkurbatov** [comment]
To correct first problem file name should be provided as filename[0] which causes to get info only for first frame of multiframe images and works even for one-frame images.

To solve another problem easyimage should run format with '%n' - this returns number of framse. So the whole solution is: a) run format '%n', get number of frames and in case it more than 1 run format with filename '[0]' appended to it. I'll try to make a patch.

**Comment by lfender6445** [comment]
Any updates on the issue? I can confirm the issue still occurs

```json
{ type: 'gif',
  depth: 8,
  width: 359,
  height: 244,
  size: 270000,
  density: { x: 72, y: 72 },
  name: 'rs-hero-1482800654671.gifGIF 8 359 244 270KB 72 72 rs-hero-1482800654671.gifGIF 8 359 244 270KB 72 72 rs-hero-1482800654671.gifGIF 8 359 244 270KB 72 72 rs-hero-1482800654671.gifGIF 8 359 244 270KB 72 72 rs-hero-1482800654671.gif',
  path: './public/tmp/rs-hero-1482800654671.gif' }
```

**Comment by mrkmg** [comment]
Could you please upload an example gif? This way I can add it to a test and then fix the issue.

**Comment by kachurovskiy** [comment]
Here's one I'm having trouble with: https://imgur.com/a/cizb1

`Easyimg error Error: identify: unable to open image 'C:\...': No such file or directory @ error/blob.c/OpenBlob/3335.                                                                                                                                                                                                                                      at C:\eprojects\powcast\node_modules\easyimage\lib\execute.js:53:33                                                               at ChildProcess.exithandler (child_process.js:224:5)                                                                              at emitTwo (events.js:106:13)                                                                                                     at ChildProcess.emit (events.js:194:7)                                                                                            at maybeClose (internal/child_process.js:899:16)                                                                                  at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) `

**Comment by kachurovskiy** [comment]
Kevin, updating to 3.0.0 solved the problem. Huge thanks!
