### ISSUE TITLE
Please add key

### ISSUE THREAD

**Issue by vitaseg** [hacksparrow/node-easyimage#79]
Please add
args.push('-coalesce')
in resize function between 
args.push('-auto-orient')
and
args.push('-resize')

must be
args.push('-auto-orient')
args.push('-coalesce')
args.push('-resize')

it fixed resize some animated gifs.
without that key some animated gifs is broke
Thank you very much

**Comment by mrkmg** [comment]
For this, I believe adding a coalesce option, so users can choose when they want it, would be the best approach.

**Comment by mrkmg** [comment]
Fixed in v3
