### ISSUE TITLE
Note: the current version does not work under Windows.

### ISSUE THREAD

**Issue by shanemcquillan** [hacksparrow/node-easyimage#8]
This is more of a non-issue!

I've installed ImageMagick on my machine and downloaded node-easyimage using NPM. I'm able to run test.js without issue, so I'm curious as to why you've stated it does not work under Windows. Am I missing something?

**Comment by jshin49** [comment]
@shanemcquillan I know this is an old thread, but can you help me out going through this with Node? 
I've installed ImageMagick on my machine on Windows 10, but I keep get this error: ImageMagick Not Found
 EasyImage requires ImageMagick to work. Install it from http://www.imagemagick.org/script/binary-releases.php.

with the following code:

easyimg.convert({src:'src.jpg', dst:'out.png', quality:100}, function(err, stdout, stderr) {
  if (err) throw err;
  something();
}

**Comment by semy** [comment]
Easyimage does not work on windows. ImageMagick use the command "convert" and on windows there is already a converte.exe from windows directly...

Any idea for a work around?
