### ISSUE TITLE
Convert large PNG to multiple page PDF

### ISSUE THREAD

**Issue by tylerevans** [hacksparrow/node-easyimage#80]
Hi

Currently I have a large PNG (1280px \* 8000px) and am converting it into a PDF.

The conversion works, however it's converting it into a single page PDF. So when I open it, I have to zoom in 800% just to see it. How can I force this to create a PDF, but with multiple pages so when I open it, it will display normally.

I'm using

easyimg.exec('convert -density 288  ' + temporaryPNG + '.png ' + temporaryPDF)

**Comment by hacksparrow** [comment]
I will working on this and other open issue in the 1st week of June.

**Comment by tylerevans** [comment]
bump- was there an update for this? Basically an option to produce multi-page PDF's as opposed to all in one (requiring heavy zoom).

**Comment by mrkmg** [comment]
I am not aware of a command that can be passed to ImageMagick to have it create a multi-page PDF. Please provide a sample ImageMagick command that would achieve what you want.

**Comment by mrkmg** [comment]
From what I can tell, this is not possible with just ImageMagick.
