### ISSUE TITLE
Invalid Parameter - -auto-orient

### ISSUE THREAD

**Issue by rneogy** [hacksparrow/node-easyimage#81]
Whenever I try cropping or rescropping an image (only things I've tried), the command passes in a parameter called "-auto-orient." I don't know where it's getting this, as it doesn't appear in any of the documentation, but due to this addition, the command fails with an invalid parameter error. How does one go about fixing this?

**Comment by mrkmg** [comment]
Which version of ImageMagick are you using?

**Comment by mrkmg** [comment]
From what I can see, -auto-orient has been available since at least 6.3.1.

**Comment by mrkmg** [comment]
Closing due to no feedback. All documentation I can find shows that -auto-orient is available.
