### ISSUE TITLE
spawn ENOMEM unhandled exception

### ISSUE THREAD

**Issue by logidelic** [hacksparrow/node-easyimage#85]
Hey all,

I recently ran into the following exception which crashed my node server:

```
FATAL: exitHandler - exception - Error: spawn ENOMEM
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at exports.execFile (child_process.js:151:15)
    at info (/home/logidelic/dev/proj/node/node_modules/easyimage/easyimage.js:54:10)
    at imgThumbnail (/home/logidelic/dev/proj/node/node_modules/easyimage/easyimage.js:412:3)
    at /home/logidelic/dev/proj/node/node_modules/easyimage/easyimage.js:112:4
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19) - spawn ENOMEM 

```

I was calling easyimage as follows:

```
easyimg.thumbnail({...}).then(function(image) {
    //...
}, function(err) {
    //...error
});

```

But the above exception was not caught by easyimage and relayed to its error handler (as I might have expected). Two questions:
1. If I wrap my easyimage call into a try...catch, would I have caught this? Unfortunately I haven't been able to repro the exception, so I can't test to be sure...
2. What might have caused this? The obvious suggests an actual "out of memory" condition, but I'm not convinced that was actually the case...

Thanks!

**Comment by derMani** [comment]
Got the same problem here: 

```
0|app      | 2017-09-26 12:23 +00:00: Error: spawn ENOMEM
0|app      |     at exports._errnoException (util.js:1022:11)
0|app      |     at ChildProcess.spawn (internal/child_process.js:313:11)
0|app      |     at exports.spawn (child_process.js:380:9)
0|app      |     at exports.execFile (child_process.js:143:15)
0|app      |     at info (/home/nodejs/oma/node_modules/easyimage/easyimage.js:54:10)
0|app      |     at imgThumbnail (/home/nodejs/oma/node_modules/easyimage/easyimage.js:412:3)
0|app      |     at /home/nodejs/oma/node_modules/easyimage/easyimage.js:112:4
0|app      |     at FSReqWrap.cb [as oncomplete] (fs.js:257:19)

```
I've observed the free memory with top, it wasn't out of memory at all

**Comment by mrkmg** [comment]
Please try the latest release, 2.2.0, to see if this issue is still present.

**Comment by mrkmg** [comment]
@derMani can you please post the exact command you are using along with the image causing the problem?

**Comment by mrkmg** [comment]
Closing this due to no feedback. If this is still an issue, just post here and I will re-open it.
