### ISSUE TITLE
Make thumbnails with streaming

### ISSUE THREAD

**Issue by PawanSasanka** [hacksparrow/node-easyimage#86]
How can i Make thumbnails by streaming image from mongoDB

**Comment by mrkmg** [comment]
I am not very familiar with how binary data is saved in the MongoDB, but the general idea would be:

1. Save the binary data to a temporary file.
2. Run the EasyImage command your want with src being your temporary file, and dst being another temporary file
3. Read in the binary data of the dst temp file.
4. Remove both temporary files
5. Save your thumbnail binary data into mongo
