### ISSUE TITLE
resizing output image with incorrect size

### ISSUE THREAD

**Issue by gsabran** [hacksparrow/node-easyimage#90]
if I've a 100x200 image and I want to resize it to a width of 50, ie a 50% reduction, I might do:

```js
easyimg.resize({
 src: ...,
  width: 50
});
```

but since the[ height will be set to the width by default](https://github.com/hacksparrow/node-easyimage/blob/9d6ef711fd9c6d08118102f1f348b4e0e03f24ba/easyimage.js#L230) and the [aspect ratio is conserved](https://github.com/hacksparrow/node-easyimage/blob/9d6ef711fd9c6d08118102f1f348b4e0e03f24ba/easyimage.js#L253),
the image will be resized to `50x50` respecting the aspect ratio. It seems that `convert` gives preference to the height, so I'll end up with an image of height `50` and width `25`. So should not
```js
if (options.width === undefined) return deferred.reject(error_messages['dim']);
options.height = options.height || options.width;
```

become
```js
if (options.height === undefined) return deferred.reject(error_messages['dim']);
options.width = options.width || options.height;
```

and `error_messages['dim']` be updated ?

**Comment by mrkmg** [comment]
This will be considered for version 3 as it could potentially break existing usage.

**Comment by mrkmg** [comment]
Fixed in v3
