### ISSUE TITLE
The 2.2 used a console.debug. will crash the app

### ISSUE THREAD

**Issue by yimity** [hacksparrow/node-easyimage#96]
console.debug in many versions node will has no debug method on console.

**Comment by mrkmg** [comment]
Hmm, I guess I'll just have to use Console . log.

Expect a patch tomorrow.

**Comment by mrkmg** [comment]
Just curious, is there a reason to not update to 3.0.0?

**Comment by mrkmg** [comment]
Version 2.2.1 released with fix.
