### ISSUE TITLE
support extent

### ISSUE THREAD

**Issue by chenghung** [hacksparrow/node-easyimage#99]
is it possible to support extent and customize size of thumbnail such as '320x320^'

```
convert -define jpeg:size=320x320 ./IMG_0014.JPG -thumbnail 320x320^ -gravity center -extent 320x320 -auto-orient  result2.jpg
```

**Comment by mrkmg** [comment]
Currently, extent is not handled by the built in functions.

If you wanted to replicate the command you have above, you would need to use the `execute` function.

```
import {execute} from "easyimage";

var result = await execute("convert", [
    "-define", "jpeg:size=320x320",
    "-thumbnail", "320x320^",
    "-gravity", "center",
    "-extent", "320x320",
    "-auto-orient",
    "./IMG_0014.JPG",
    "result2.jpg",
]);
```

This library is intended to be used for very simple and straight-forward modifications, without too many options. For advanced usage, there are [larger](https://www.npmjs.com/package/gm) libraries which use ImageMagick under the hood, and offer a pragmatic approach to all or most of the features of ImageMagick.

That is not to say I am not open to adding more features to this library, but I would want to make sure that it is clear how it is to be used.
